name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
        rails:
          - "5.2"
          - "6.0"
          - "6.1"
          - main
        exclude:
          - ruby: 2.5
            rails: main
          - ruby: 2.6
            rails: main
          - ruby: 3.0
            rails: "5.1"
          - ruby: 3.0
            rails: "5.2"

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.activerecord-${{ matrix.rails }}.x

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rspec spec
